version: "3.9"

services:
  wordpress:
    depends_on:
      - wpdb
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/pmsite-docs
    ports:
      - "6100:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  wpdb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wpcli:
    image: wordpress:cli
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/pmsite-docs
      - ./db:/var/www/html/db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      ABSPATH: /usr/src/wordpress/

volumes:
  db_data: {}
  wordpress_data: {}
